import { join } from 'node:path'
import { createStorage } from 'unstorage'
import fsDriver from 'unstorage/drivers/fs'

const dataStorage = createStorage({
  driver: fsDriver({
    base: join(process.cwd(), '.data'),
  }),
})

const cssStorage = createStorage({
  driver: fsDriver({
    base: join(process.cwd(), 'app', 'assets'),
  }),
})

const breakpoints: Record<string, string> = {
  tablet: '768px',
  desktop: '1024px',
  largeDesktop: '1280px',
}

function generateCss(sizes: Record<string, number>): string {
  let css = `/* Title Font — generated by /api/font-sizes */\n`
  css += `.title-font {\n`
  css += `  font-family: 'EnduroWeb, sans-serif';\n`
  css += `  letter-spacing: 0.03em;\n`
  css += `  text-transform: uppercase;\n`
  css += `  line-height: 1;\n`
  css += `  display: block;\n`
  css += `  font-size: ${sizes.mobile}rem;\n}\n`

  for (const [key, minWidth] of Object.entries(breakpoints)) {
    css += `\n@media (min-width: ${minWidth}) {\n`
    css += `  .title-font {\n    font-size: ${sizes[key]}rem;\n  }\n`
    css += `}\n`
  }

  return css
}

export default defineEventHandler(async (event) => {
  const body = await readBody(event)

  if (!body || typeof body !== 'object') {
    throw createError({ statusCode: 400, message: 'Request body must be a JSON object' })
  }

  const keys = ['mobile', 'tablet', 'desktop', 'largeDesktop'] as const
  const fontSizes: Record<string, number> = {}

  for (const key of keys) {
    if (typeof body[key] !== 'number' || body[key] <= 0) {
      throw createError({ statusCode: 400, message: `"${key}" must be a positive number` })
    }
    fontSizes[key] = body[key]
  }

  await dataStorage.setItem('font-sizes.json', fontSizes)
  await cssStorage.setItemRaw('fonts.css', generateCss(fontSizes))

  return { success: true, fontSizes }
})
