import { d as defineEventHandler, g as getAuthenticatedPb, b as readBody, c as createError, a as createStorage } from '../../nitro/nitro.mjs';
import { join } from 'node:path';
import process from 'node:process';
import { f as fsDriver } from '../../_/fs.mjs';
import 'pocketbase';
import 'node:http';
import 'node:https';
import 'node:events';
import 'node:buffer';
import 'node:fs';
import 'node:crypto';
import 'node:url';
import '@iconify/utils';
import 'consola';
import 'ipx';
import 'anymatch';

const dataStorage = createStorage({
  driver: fsDriver({
    base: join(process.cwd(), ".data")
  })
});
const cssStorage = createStorage({
  driver: fsDriver({
    base: join(process.cwd(), "app", "assets")
  })
});
const breakpoints = {
  tablet: "768px",
  desktop: "1024px",
  largeDesktop: "1280px"
};
function generateCss(sizes) {
  let css = `/* Title Font \u2014 generated by /api/font-sizes */
`;
  css += `.title-font {
`;
  css += `  font-family: 'EnduroWeb', sans-serif;
`;
  css += `  letter-spacing: 0.03em;
`;
  css += `  text-transform: uppercase;
`;
  css += `  line-height: 1;
`;
  css += `  display: block;
`;
  css += `  font-size: ${sizes.mobile}rem;
}
`;
  for (const [key, minWidth] of Object.entries(breakpoints)) {
    css += `
@media (min-width: ${minWidth}) {
`;
    css += `  .title-font {
    font-size: ${sizes[key]}rem;
  }
`;
    css += `}
`;
  }
  return css;
}
const fontSizes_put = defineEventHandler(async (event) => {
  getAuthenticatedPb(event);
  const body = await readBody(event);
  if (!body || typeof body !== "object") {
    throw createError({ statusCode: 400, message: "Request body must be a JSON object" });
  }
  const keys = ["mobile", "tablet", "desktop", "largeDesktop"];
  const fontSizes = {};
  for (const key of keys) {
    if (typeof body[key] !== "number" || body[key] <= 0) {
      throw createError({ statusCode: 400, message: `"${key}" must be a positive number` });
    }
    fontSizes[key] = body[key];
  }
  await dataStorage.setItem("font-sizes.json", fontSizes);
  await cssStorage.setItemRaw("fonts.css", generateCss(fontSizes));
  return { success: true, fontSizes };
});

export { fontSizes_put as default };
//# sourceMappingURL=font-sizes.put.mjs.map
